services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    volumes:
      - ./server:/server


